version: '3'
services:
  # Servidor de Woodpecker CI
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    restart: always
    environment:
      WOODPECKER_SERVER_ADDR: ":8000"
      WOODPECKER_AGENT_SECRET: myagentsecret
      WOODPECKER_ADMIN: yourusername  # El administrador del sistema
      WOODPECKER_OPEN: "true"
      WOODPECKER_GITEA: "true"  # Asume integración con Gitea
      WOODPECKER_GITEA_URL: http://gitea:3000
      WOODPECKER_GITEA_CLIENT: your-client-id
      WOODPECKER_GITEA_SECRET: your-client-secret
    ports:
      - "8000:8000"  # Puerto para acceder a la interfaz web
    volumes:
      - ./woodpecker-data:/var/lib/woodpecker  # Almacenar datos del servidor

  # Agente Woodpecker CI
  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent
    restart: always
    environment:
      WOODPECKER_SERVER: woodpecker-server:9000
      WOODPECKER_AGENT_SECRET: myagentsecret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Permitir que el agente ejecute Docker
